# Author: Ryan Kirk

AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Base template that deploys the ECS Scaling Schedule for target env

Parameters:
  ProjectName:
    Description: Standard Name identifying project
    Type: String
  EnvName:
    Description: Name of the environment
    Type: String
  TemplateRootURL:
    Description: Root URL to access S3 bucket containing CF Templates
    Type: String
  TemplateBucket:
    Description: S3 bucket containing CF Templates
    Type: String
  Codebucket:
    Type: String
    Description: Bucket where the python code for lambda is saved
  CodeKey:
    Type: String
    Description: The S3 object key
    Default: "lambda_function.zip"
  EcsFullPermissionRole:
    Type: String
    Description: ARN of the AWS managed IAM Role for ECS Full Access permissions e.g arn:aws:iam::aws:policy/AmazonECS_FullAccess
    Default: "arn:aws:iam::aws:policy/AmazonECS_FullAccess"


Resources:
  ECSScalingScheduler:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.${TemplateRootURL}/ecs-scaling-scheduler.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvName: !Ref EnvName
        Codebucket: !Ref Codebucket
        CodeKey: !Ref CodeKey
        ClusterName: !Sub ${ProjectName}-${EnvName}-ecs-cluster
